### ISSUE TITLE
Some things in this pack are just... wrong

### ISSUE THREAD

**Issue by huhenU** [AtlasNX/Kosmos-Wii-U#2]
Ok, so:
1. Why are you recommending the normal savemii version? The modded one (found here: https://github.com/GabyPCgeeK/savemii/releases) is the better one.
2. Your "boot mocha automatically" commit just made the haxchi config even worse than it was before. Haxchi already applies cfw when launching sysmenu, so just set "default=sysmenu" and "a=pathtohomebrew". That will still run cfw without the need of mocha (or without the need of an SD card even). I can see why some devs autoboot mocha through haxchi, and it also made sense back when redNAND was used, but with your current mocha-config, it adds nothing but extra seconds to the boot time.
(3. cbhc is missing, which is fine if not covered by whatever guide is being used but for a complete setup, there's no reason to not have it [even if it's an optional step])

**Comment by huhenU** [comment]
I also noticed you're including savemii and hid_to_vpad probably as a few recommended homebrew apps, but imo there are missing some things like sdcafiine, tcpgecko, disc2app, and other essential apps

**Comment by AnnsAnns** [comment]
1. Will fix
2. Maschell and I discussed it and agreed that Mocha should always be launched.
3. Coldboot Haxchi will not be supported by the guide (as said in the guide)

**Comment by AnnsAnns** [comment]
> 
> 
> I also noticed you're including savemii and hid_to_vpad probably as a few recommended homebrew apps, but imo there are missing some things like sdcafiine, tcpgecko, disc2app, and other essential apps

Feel free to submit recommended apps. I personally didn't find any reason to include these apps when including the appstore.

**Comment by AnnsAnns** [comment]
Fixed in newest commit
