### ISSUE TITLE
Haxchi not compatible with the latest version of Homebrew Launcher

### ISSUE THREAD

**Issue by ghost** [AtlasNX/Kosmos-Wii-U#6]
In the `dev` branch:

Haxchi is not compatible with the latest version of the Homebrew Launcher.
On https://github.com/FIX94/haxchi, it says,
> This also ONLY LOADS THE .ELF VERSION OF THE HOMBEBREW LAUNCHER which as of right now is v1.4 so make sure to keep that on your sd card or you will just get error -5 when starting your haxchi channel. Once you are in the homebrew launcher it is also perfectly compatible with loading .rpx files, you just cant use haxchi itself to load .rpx files.

However, the Homebrew Launcher produced by the builder script is v2.1, which is an `.rpx` file, so it cannot be loaded by Haxchi.

One way to fix this would be to also include a copy of the `.elf` Homebrew Launcher v1.4 in the `haxchi` folder and change the `haxchi/config.txt` to this:
```
b=sysmenu
a=haxchi/homebrew_launcher.elf
default=wiiu/apps/mocha/mocha.elf
```
(Also, Haxchi currently boots Haxchi CFW automatically instead of Mocha CFW so this would fix that as well)

**Comment by AnnsAnns** [comment]
That's how we also had it before though. We also have the homebrew launcher as an .elf launching.
https://github.com/AtlasNX/WiiU-Kosmos/blob/master/Package/haxchi/config.txt

**Comment by nicholemattera** [comment]
This was an issue for the dev branch.

**Comment by nicholemattera** [comment]
Thanks for the heads up! ;)
